version: '3.8'
services:

  spark-client:
    container_name: spark-client
    image: spark_client
    ports:
      - "8000:8000"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/notebooks
      - ./data:/home/data

  spark-master:
    container_name: spark-master
    image: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/home/data
    environment:
      - SPARK_WORKLOAD=master
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  spark-worker-1:
    image: spark
    container_name: worker_1
    ports:
      - "9001:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
    volumes:
      - ./data:/home/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  spark-worker-2:
    image: spark
    container_name: worker_2
    ports:
      - "9002:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
    volumes:
      - ./data:/home/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
